# Generated by Django 3.2.8 on 2021-12-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo2', '0002_auto_20211227_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='insects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/insect')),
            ],
        ),
        migrations.RenameModel(
            old_name='insect',
            new_name='travels',
        ),
    ]
