# Generated by Django 3.2.8 on 2021-12-30 18:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo2', '0004_alter_bird_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images/bird'),
        ),
    ]
