# Generated by Django 3.2.8 on 2021-12-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo2', '0005_alter_bird_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.ImageField(upload_to='images/bird'),
        ),
    ]
